name: trueface_libraries_docs
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.4
  responsive_builder: ^0.6.4
  flutter_markdown: ^0.6.14
  url_launcher: ^6.1.10
  google_fonts: ^4.0.3
  markdown: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

    - assets/v2.1/
    - assets/v2.1/images/
    - assets/v2.1/android/
    - assets/v2.1/c/
    - assets/v2.1/dotnet/
    - assets/v2.1/ios/
    - assets/v2.1/ios/images/

    - assets/v1.6/
    - assets/v1.6/images/
    - assets/v1.6/android/
    - assets/v1.6/c/
    - assets/v1.6/dotnet/
    - assets/v1.6/ios/
    - assets/v1.6/ios/images/

    - assets/v1.5/
    - assets/v1.5/images/
    - assets/v1.5/android/
    - assets/v1.5/c/
    - assets/v1.5/dotnet/
    - assets/v1.5/ios/
    - assets/v1.5/ios/images/

    - assets/v1.4/
    - assets/v1.4/images/
    - assets/v1.4/android/
    - assets/v1.4/c/
    - assets/v1.4/dotnet/
    - assets/v1.4/ios/
    - assets/v1.4/ios/images/

    - assets/v1.3/
    - assets/v1.3/images/
    - assets/v1.3/android/
    - assets/v1.3/c/
    - assets/v1.3/dotnet/
    - assets/v1.3/ios/
    - assets/v1.3/ios/images/

    - assets/v1.1/
    - assets/v1.1/images/
    - assets/v1.1/android/
    - assets/v1.1/c/
    - assets/v1.1/dotnet/
    - assets/v1.1/ios/
    - assets/v1.1/ios/images/

    - assets/v0.8/
    - assets/v0.8/images/
    - assets/v0.8/android/
    - assets/v0.8/c/
    - assets/v0.8/dotnet/
    - assets/v0.8/ios/
    - assets/v0.8/ios/images/
