name: trueface_libraries_docs
description: Trueface SDK documentation site.

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  go_router: ^14.6.2
  markdown_widget: ^2.3.2+8
  flutter_highlight: ^0.7.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1

dependency_overrides:
  http: ^1.3.0
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

    - assets/v3.0/
    - assets/v3.0/images/
    - assets/v3.0/android/
    - assets/v3.0/c/
    - assets/v3.0/dotnet/
    - assets/v3.0/ios/
    - assets/v3.0/ios/images/

    - assets/v2.4/
    - assets/v2.4/images/
    - assets/v2.4/android/
    - assets/v2.4/c/
    - assets/v2.4/dotnet/
    - assets/v2.4/ios/
    - assets/v2.4/ios/images/

    - assets/v2.1/
    - assets/v2.1/images/
    - assets/v2.1/android/
    - assets/v2.1/c/
    - assets/v2.1/dotnet/
    - assets/v2.1/ios/
    - assets/v2.1/ios/images/

    - assets/v1.6/
    - assets/v1.6/images/
    - assets/v1.6/android/
    - assets/v1.6/c/
    - assets/v1.6/dotnet/
    - assets/v1.6/ios/
    - assets/v1.6/ios/images/

    - assets/v1.5/
    - assets/v1.5/images/
    - assets/v1.5/android/
    - assets/v1.5/c/
    - assets/v1.5/dotnet/
    - assets/v1.5/ios/
    - assets/v1.5/ios/images/

    - assets/v1.4/
    - assets/v1.4/images/
    - assets/v1.4/android/
    - assets/v1.4/c/
    - assets/v1.4/dotnet/
    - assets/v1.4/ios/
    - assets/v1.4/ios/images/

    - assets/v1.3/
    - assets/v1.3/images/
    - assets/v1.3/android/
    - assets/v1.3/c/
    - assets/v1.3/dotnet/
    - assets/v1.3/ios/
    - assets/v1.3/ios/images/

    - assets/v1.1/
    - assets/v1.1/images/
    - assets/v1.1/android/
    - assets/v1.1/c/
    - assets/v1.1/dotnet/
    - assets/v1.1/ios/
    - assets/v1.1/ios/images/

    - assets/v0.8/
    - assets/v0.8/images/
    - assets/v0.8/android/
    - assets/v0.8/c/
    - assets/v0.8/dotnet/
    - assets/v0.8/ios/
    - assets/v0.8/ios/images/
